
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 18 00:07:03 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 36;
  public static final int LBRACKET = 7;
  public static final int CONST = 9;
  public static final int CASE = 22;
  public static final int NOTEQUAL = 34;
  public static final int LPAREN = 5;
  public static final int GREATER = 29;
  public static final int SEMI = 11;
  public static final int CONTINUE = 17;
  public static final int MINUS = 39;
  public static final int LESS = 31;
  public static final int FOR = 23;
  public static final int CHARACTER = 48;
  public static final int RPAREN = 6;
  public static final int AND = 42;
  public static final int OR = 41;
  public static final int BOOL = 47;
  public static final int QMARK = 43;
  public static final int COMMA = 13;
  public static final int INC = 25;
  public static final int PLUS = 38;
  public static final int MULTIPLY = 35;
  public static final int ASSIGN = 10;
  public static final int LESSEQ = 32;
  public static final int IF = 14;
  public static final int DOT = 27;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int RBRACKET = 8;
  public static final int EQUAL = 33;
  public static final int NEW = 44;
  public static final int error = 1;
  public static final int NUMBER = 46;
  public static final int MOD = 37;
  public static final int IDENT = 49;
  public static final int BREAK = 16;
  public static final int VOID = 12;
  public static final int SWITCH = 21;
  public static final int COLON = 24;
  public static final int LBRACE = 3;
  public static final int ELSE = 15;
  public static final int ENUM = 28;
  public static final int READ = 19;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int GREATEREQ = 30;
  public static final int DEC = 26;
  public static final int MAX = 45;
  public static final int LENGTH = 40;
  public static final int PRINT = 20;
}

